import "./globals.css";
import { Outfit } from "next/font/google";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

export const metadata = {
  title: "AI Note-Taking App",
  description: "Smart AI-powered note-taking from PDFs",
};

// Font in Next.js
const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${outfit.className}  min-h-screen bg-gradient-to-b from-pink-50 via-white to-blue-100 text-black`}
        
        >
          <Provider>{children}</Provider>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}


// import "./globals.css";
// import {Outfit} from "next/font/google";
// import Provider from "./provider";
// import { ClerkProvider } from "@clerk/nextjs";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// // font in next js 
// const outfit = Outfit({subsets:['latin']})

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
      
//     <html lang="en">
//       <body
//       className={outfit.className}
//       >
//      <Provider>{children}</Provider>
       
//       </body>
//     </html>
//     </ClerkProvider>
//   );
// }
